/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sellyourself.screns;

import br.com.sellyourself.controls.CadCliente;
import br.com.sellyourself.dao.ClienteDao;
import br.com.sellyourself.entities.Cliente;
import br.com.sellyourself.reports.RepCliente;
import br.com.wentzel.persistencia.clauses.Where;
import br.com.wentzel.persistencia.main.UtilDao;
import br.com.wentzel.util.UtilTable;
import br.com.wentzel.views.ConsultaCad;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.dynamicreports.report.datasource.DRDataSource;

/**
 *
 * @author Matheus
 */
public class FCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadTipoServico
     */
    private CadCliente controle;
    private ClienteDao dao;
    private Cliente object;
    private ArrayList<Cliente> objects;
    private int estado; //1 = inserindo / 2 = editando

    public FCliente() {
        initComponents();
        init();
    }

    private void init() {

        this.dao = new ClienteDao();
        this.object = new Cliente();
        this.objects = new ArrayList();
        this.controle = new CadCliente(this, dao, object, objects);
        this.estado = 1;

        this.Id_cliente.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

    }

    private void updateControl() {

        this.controle = new CadCliente(this, dao, object, objects);

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        Descricao6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jbOk = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Id_cliente = new javax.swing.JTextField();
        jbProcurar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbProcurar1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Nome_fantasia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Telefone = new javax.swing.JTextField();
        Tipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Documento = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Rua = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Bairro = new javax.swing.JTextField();
        Cidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Cep = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jLabel10.setText("Documento*:");

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Cadastro | Cliente");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setText("Nome:*");

        jbOk.setText("Salvar");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod.:");

        Id_cliente.setEditable(false);
        Id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_clienteActionPerformed(evt);
            }
        });

        jbProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sellyourself/icons/search.png"))); // NOI18N
        jbProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProcurarActionPerformed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sellyourself/icons/trash.png"))); // NOI18N
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jLabel3.setText("* - Campos Obrigatórios");

        jbProcurar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sellyourself/icons/printer.png"))); // NOI18N
        jbProcurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProcurar1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome Fantasia:");

        jLabel5.setText("Telefone*:");

        Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "F", "J" }));
        Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoActionPerformed(evt);
            }
        });

        jLabel6.setText("Tipo*:");

        jLabel7.setText("Documento*:");

        jLabel8.setText("Rua*:");

        jLabel9.setText("Bairro*:");

        jLabel11.setText("Cidade*:");

        jLabel12.setText("Cep*:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(207, 207, 207))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(Id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbProcurar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jbProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(Nome_fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8)
                            .addComponent(Rua, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addComponent(Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProcurar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome_fantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbCancelar)
                            .addComponent(jbOk))
                        .addContainerGap())
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed

        if (controle.validView()) {

            if (estado == 1) {

                updateControl();
                controle.insert();
                controle.cleanView();

                JOptionPane.showMessageDialog(rootPane, "Cliente adicionado com sucesso!");

            } else if (estado == 2) {

                updateControl();
                controle.update();
                controle.cleanView();

                JOptionPane.showMessageDialog(rootPane, "Cliente alterado com sucesso!");

                this.estado = 1;

            }

        }

    }//GEN-LAST:event_jbOkActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed

        controle.cleanView();

        this.Id_cliente.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

        this.estado = 1;


    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcurarActionPerformed

        ConsultaCad cc = new ConsultaCad(null, true, object, dao) {
            @Override
            public void configTable() {

                UtilTable.centerTable(getJtTabela(), 0);

                UtilTable.setSizeColumn(getJtTabela(), 0, 30);
                UtilTable.setSizeColumn(getJtTabela(), 1, 200);

            }
        };
        cc.setSize(400, 300);
        cc.setVisible(true);

        if (cc.getObject() instanceof Cliente && cc.getObject() != null) {
            this.object = (Cliente) cc.getObject();

            updateControl();
            this.controle.setView();
            this.estado = 2;
        } else {
            System.err.println("Erro ao retornar o Cliente");
            this.object = new Cliente();
            init();

            this.estado = 1;
        }

    }//GEN-LAST:event_jbProcurarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        controle.cleanView();

        this.Id_cliente.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

        this.estado = 1;

    }//GEN-LAST:event_formInternalFrameClosing

    private void Id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_clienteActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed

        if (estado == 2) {

            if (JOptionPane.showConfirmDialog(this, "Você deseja excluir este registro?") == 0) {

                dao.delete(object, new Where(object.getPRIMARYKEY() + " = " + object.getId_cliente()));

                controle.cleanView();

                this.Id_cliente.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

                this.estado = 1;

            }

        }

    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbProcurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcurar1ActionPerformed

        int escolha = 0;
        escolha = JOptionPane.showConfirmDialog(this, "Você deseja imprimir uma listagem do cadastro de Cliente?");

        if (escolha == 0) {
            RepCliente rGP = new RepCliente();
            Cliente obj = new Cliente();
            ClienteDao gpDao = new ClienteDao();

            DRDataSource drDS = gpDao.getDataSource(obj);

            rGP.build(drDS);
        }


    }//GEN-LAST:event_jbProcurar1ActionPerformed

    private void TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoActionPerformed

    //Getters and Setters
    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public JTextField getBairro() {
        return Bairro;
    }

    public void setBairro(JTextField Bairro) {
        this.Bairro = Bairro;
    }

    public JTextField getCep() {
        return Cep;
    }

    public void setCep(JTextField Cep) {
        this.Cep = Cep;
    }

    public JTextField getCidade() {
        return Cidade;
    }

    public void setCidade(JTextField Cidade) {
        this.Cidade = Cidade;
    }

    public JTextField getDescricao6() {
        return Descricao6;
    }

    public void setDescricao6(JTextField Descricao6) {
        this.Descricao6 = Descricao6;
    }

    public JTextField getDocumento() {
        return Documento;
    }

    public void setDocumento(JTextField Documento) {
        this.Documento = Documento;
    }

    public JTextField getId_cliente() {
        return Id_cliente;
    }

    public void setId_cliente(JTextField Id_cliente) {
        this.Id_cliente = Id_cliente;
    }

    public JTextField getNome() {
        return Nome;
    }

    public void setNome(JTextField Nome) {
        this.Nome = Nome;
    }

    public JTextField getNome_fantasia() {
        return Nome_fantasia;
    }

    public void setNome_fantasia(JTextField Nome_fantasia) {
        this.Nome_fantasia = Nome_fantasia;
    }

    public JTextField getRua() {
        return Rua;
    }

    public void setRua(JTextField Rua) {
        this.Rua = Rua;
    }

    public JTextField getTelefone() {
        return Telefone;
    }

    public void setTelefone(JTextField Telefone) {
        this.Telefone = Telefone;
    }

    public JComboBox<String> getTipo() {
        return Tipo;
    }

    public void setTipo(JComboBox<String> Tipo) {
        this.Tipo = Tipo;
    }
    
    

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bairro;
    private javax.swing.JTextField Cep;
    private javax.swing.JTextField Cidade;
    private javax.swing.JTextField Descricao6;
    private javax.swing.JTextField Documento;
    private javax.swing.JTextField Id_cliente;
    private javax.swing.JTextField Nome;
    private javax.swing.JTextField Nome_fantasia;
    private javax.swing.JTextField Rua;
    private javax.swing.JTextField Telefone;
    private javax.swing.JComboBox<String> Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbOk;
    private javax.swing.JButton jbProcurar;
    private javax.swing.JButton jbProcurar1;
    // End of variables declaration//GEN-END:variables
}
