/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sellyourself.screns;

import br.com.sellyourself.controls.CadProduto;
import br.com.sellyourself.dao.GrupoProdutoDao;
import br.com.sellyourself.dao.ProdutoDao;
import br.com.sellyourself.entities.GrupoProduto;
import br.com.sellyourself.entities.Produto;
import br.com.sellyourself.reports.RepProduto;
import br.com.wentzel.persistencia.clauses.Where;
import br.com.wentzel.persistencia.main.UtilDao;
import br.com.wentzel.util.UtilGeral;
import br.com.wentzel.util.UtilTable;
import br.com.wentzel.views.ConsultaCad;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.dynamicreports.report.datasource.DRDataSource;

/**
 *
 * @author Matheus
 */
public class FProduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadTipoServico
     */
    private CadProduto controle;
    private ProdutoDao dao;
    private Produto object;
    private ArrayList<Produto> objects;
    private int estado; //1 = inserindo / 2 = editando

    public FProduto() {
        initComponents();
        init();
    }

    private void init() {

        this.dao = new ProdutoDao();
        this.object = new Produto();
        this.objects = new ArrayList();
        this.controle = new CadProduto(this, dao, object, objects);
        this.estado = 1;

        this.Id_produto.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

    }

    private void updateControl() {

        this.controle = new CadProduto(this, dao, object, objects);

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Descricao = new javax.swing.JTextField();
        jbOk = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Id_produto = new javax.swing.JTextField();
        jbProcurar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Ean = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Unidade = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Valor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Grupo_id = new javax.swing.JTextField();
        jbProcurar1 = new javax.swing.JButton();
        jbProcurar2 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Cadastro | Produto");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel2.setText("Descrição:*");

        jbOk.setText("Salvar");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod.:");

        Id_produto.setEditable(false);
        Id_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_produtoActionPerformed(evt);
            }
        });

        jbProcurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sellyourself/icons/search.png"))); // NOI18N
        jbProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProcurarActionPerformed(evt);
            }
        });

        jbDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sellyourself/icons/trash.png"))); // NOI18N
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        jLabel3.setText("Ean:*");

        jLabel4.setText("Unidade:*");

        jLabel5.setText("Valor:*");

        jLabel6.setText("* - Campos Obrigatórios");

        jLabel7.setText("Grupo Produto:*");

        Grupo_id.setEditable(false);

        jbProcurar1.setText("Buscar");
        jbProcurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProcurar1ActionPerformed(evt);
            }
        });

        jbProcurar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sellyourself/icons/printer.png"))); // NOI18N
        jbProcurar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProcurar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(Ean, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Unidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(Id_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(241, 241, 241))
                                    .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbProcurar2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbOk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Grupo_id, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbProcurar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Id_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProcurar2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Unidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Grupo_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbProcurar1))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbCancelar)
                        .addComponent(jbOk))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed

        if (controle.validView()) {

            if (estado == 1) {

                updateControl();
                Grupo_id.setText(UtilGeral.returnIdFromIdDesc(Grupo_id.getText()));
                controle.insert();
                controle.cleanView();

                JOptionPane.showMessageDialog(rootPane, "Produto adicionado com sucesso!");

            } else if (estado == 2) {

                updateControl();
                Grupo_id.setText(UtilGeral.returnIdFromIdDesc(Grupo_id.getText()));
                controle.update();
                controle.cleanView();

                JOptionPane.showMessageDialog(rootPane, "Produto alterado com sucesso!");

                this.estado = 1;

            }

        }

    }//GEN-LAST:event_jbOkActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed

        controle.cleanView();

        this.Id_produto.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

        this.estado = 1;


    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcurarActionPerformed

        ConsultaCad cc = new ConsultaCad(null, true, object, dao) {
            @Override
            public void configTable() {

                UtilTable.centerTable(getJtTabela(), 0);

                UtilTable.setSizeColumn(getJtTabela(), 0, 30);
                UtilTable.setSizeColumn(getJtTabela(), 1, 200);

            }
        };
        cc.setSize(400, 300);
        cc.setVisible(true);

        if (cc.getObject() instanceof Produto && cc.getObject() != null) {
            this.object = (Produto) cc.getObject();

            updateControl();
            this.controle.setView();

            //Busca cadastro auxiliar
            GrupoProdutoDao gpDao = new GrupoProdutoDao();
            GrupoProduto gp = new GrupoProduto();
            ArrayList<GrupoProduto> aGp = gpDao.selectId(gp, Grupo_id.getText());
            if (aGp != null) {
                if (!aGp.isEmpty()) {
                    Grupo_id.setText(Grupo_id.getText() + " - " + aGp.get(0).getDescricao());
                }
            }

            this.estado = 2;
        } else {
            System.err.println("Erro ao retornar o Produto");
            this.object = new Produto();
            init();

            this.estado = 1;
        }

    }//GEN-LAST:event_jbProcurarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing

        controle.cleanView();

        this.Id_produto.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

        this.estado = 1;

    }//GEN-LAST:event_formInternalFrameClosing

    private void Id_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_produtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_produtoActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed

        if (estado == 2) {

            if (JOptionPane.showConfirmDialog(this, "Você deseja excluir este registro?") == 0) {

                dao.delete(object, new Where(object.getPRIMARYKEY() + " = " + object.getId_produto()));

                controle.cleanView();

                this.Id_produto.setText(UtilDao.selectProxId(object.getTABLE(), object.getPRIMARYKEY()) + "");

                this.estado = 1;

            }

        }

    }//GEN-LAST:event_jbDeletarActionPerformed

    private void jbProcurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcurar1ActionPerformed

        GrupoProduto gp = new GrupoProduto();
        GrupoProdutoDao gpDao = new GrupoProdutoDao();

        ConsultaCad cc = new ConsultaCad(null, true, gp, gpDao) {
            @Override
            public void configTable() {

                UtilTable.centerTable(getJtTabela(), 0);

                UtilTable.setSizeColumn(getJtTabela(), 0, 30);
                UtilTable.setSizeColumn(getJtTabela(), 1, 200);

            }
        };
        cc.setSize(400, 300);
        cc.setVisible(true);

        if (cc.getObject() instanceof GrupoProduto) {
            gp = (GrupoProduto) cc.getObject();

            Grupo_id.setText(gp.getId_grupo() + " - " + gp.getDescricao());

        } else {
            System.err.println("Erro ao retornar o Grupo Produto");
        }

    }//GEN-LAST:event_jbProcurar1ActionPerformed

    private void jbProcurar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProcurar2ActionPerformed
        
        int escolha = 0;
        escolha = JOptionPane.showConfirmDialog(this, "Você deseja imprimir uma listagem do cadastro de Produto?");

        if (escolha == 0) {
            RepProduto rPr = new RepProduto();
            Produto pr = new Produto();
            ProdutoDao prDao = new ProdutoDao();

            DRDataSource drDS = prDao.getDataSource(pr);

            rPr.build(drDS);
        }
        
    }//GEN-LAST:event_jbProcurar2ActionPerformed

    //Getters and Setters
    public int getEstado() {
        return estado;
    }

    public void setEstado(int estado) {
        this.estado = estado;
    }

    public JTextField getDescricao() {
        return Descricao;
    }

    public void setDescricao(JTextField Descricao) {
        this.Descricao = Descricao;
    }

    public JTextField getId_produto() {
        return Id_produto;
    }

    public void setId_produto(JTextField Id_produto) {
        this.Id_produto = Id_produto;
    }

    public JTextField getEan() {
        return Ean;
    }

    public void setEan(JTextField Ean) {
        this.Ean = Ean;
    }

    public JTextField getUnidade() {
        return Unidade;
    }

    public void setUnidade(JTextField Unidade) {
        this.Unidade = Unidade;
    }

    public JTextField getValor() {
        return Valor;
    }

    public void setValor(JTextField Valor) {
        this.Valor = Valor;
    }

    public JTextField getGrupo_id() {
        return Grupo_id;
    }

    public void setGrupo_id(JTextField Grupo_id) {
        this.Grupo_id = Grupo_id;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descricao;
    private javax.swing.JTextField Ean;
    private javax.swing.JTextField Grupo_id;
    private javax.swing.JTextField Id_produto;
    private javax.swing.JTextField Unidade;
    private javax.swing.JTextField Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbOk;
    private javax.swing.JButton jbProcurar;
    private javax.swing.JButton jbProcurar1;
    private javax.swing.JButton jbProcurar2;
    // End of variables declaration//GEN-END:variables
}
